CREATE TABLE TRADE (
	TRADE_ID NUMBER (5, 0) NOT NULL,
	SIDE VARCHAR (10) NOT NULL,
	SYMBOL VARCHAR (6) NOT NULL,
	SHARES NUMBER (4, 2) NOT NULL,
	PRICE NUMBER (4, 2) NOT NULL,
	STATE VARCHAR (20) NOT NULL,
	PRIMARY KEY (TRADE_ID)
)